New simple units fields (Task #13661)
QoboLtd/cakephp-csv-migrations pull request #822
Opened 2020-10-26 08:13 UTC by eliamariutti

2020-10-26 10:33 UTC, acrias requested changes

2020-10-26 10:33 UTC, acrias commented on webroot/js/inputmask.init.js
> +    $(':input').inputmask()
@eliamariutti I think this must be called only for those inputs that has `data-inputmask`

2020-10-26 10:37 UTC, eliamariutti commented on webroot/js/inputmask.init.js
> +    $(':input').inputmask()
@acrias it is. Check `src/Template/Element/FieldHandlers/SimpleUnitFieldHandler/input.ctp`

2020-10-26 10:40 UTC, acrias approved these changes

2020-10-27 13:11 UTC, softius approved these changes

2020-10-27 13:45 UTC, merged